- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME')}}/.ssh/id_ed25519"
    dev:       "{{ lookup('env', 'HOME')}}/dev"
  become: true
  pre_tasks:
  - name: Update Apt
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/zsh.yml
