- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key:   "{{ lookup('env', 'HOME')}}/.ssh/id_ed25519"
    dev:        "{{ lookup('env', 'HOME')}}/dev"
    user:       "{{ lookup('env', 'USER') }}"
    zsh_custom: "{{ lookup('env', 'HOME')}}/.oh-my-zsh/custom/"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/ssh.yml
      # - include: tasks/git.yml
    - include: tasks/zsh.yml
    - include: tasks/nvim.yml
    - include: tasks/tools.yml
