- hosts: localhost
  become: true
  pre_tasks:
  - name: Update Apt
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/zsh.yml
